Added tests and allure results
MaxwellDevelopments/Diplom_3 pull request #1
Opened 2024-05-30 07:18 UTC by MaxwellDevelopments

2024-06-02 14:43 UTC, pavel-ulan requested changes
аналогично прошлому заданию. довольно много оригинальной реализации, которая и не хорошая и не плохая, но просто "странная". В целом работа ок, надо поправить пару мест (но как и в прошлом, хотелось бы комментов по поводу как и почему выбрано то или иное решение)

2024-06-02 14:43 UTC, pavel-ulan commented on src/test/java/stellarburger/pom/Page.java
за стремление сделать структуру хвалю, молодцом =)

2024-06-02 14:43 UTC, pavel-ulan commented on src/test/java/stellarburger/tests/ConstructorPanelTests.java
> +        isElementSelected(selectedIngredientType);
**можно лучше**
твое желание объединить тест по принципу одинаковой логики - отличное. реализация же, немного подкачала.
вся красота решения убивается switch case конструкцией. как варик (который в том числе решает проблему bun), первым шагом кликай по рандомному разделу, который != (не равен) bun и разделу который передан в параметре. тем самым будет унификация и одинаковая реализация для любого раздела.

2024-06-02 14:43 UTC, pavel-ulan commented on src/test/java/stellarburger/tests/ConstructorPanelTests.java
> +        MatcherAssert.assertThat(cssClass, containsString("current"));
**можно лучше**
а этот метод можно было оставить в классе PO. это и структурнее и логично правильнее было бы

2024-06-02 14:43 UTC, pavel-ulan commented on src/test/java/stellarburger/tests/LoginTests.java
> +    static void deleteUser() {
я всеравно не понимаю, для чего тебе статик реализация..... будь это рабочий проект, я бы требовал убрать

2024-06-02 14:43 UTC, pavel-ulan commented on src/test/java/stellarburger/tests/RegistrationTests.java
> +        deleteUser(user);
**надо исправить**
я понимаю, что у тебя разная реализация удаления пользователя, но это не повод использовать этот метод внутри теста. Представь, что тест ломается при выполнении, соответственно до этого шага не доходит и тестовые пользаки начинают накапливаться в БД (или где-то еще).
такой метод должен быть всегда в after блоке. просто запихни туда реализацию с проверкой на существование токена. есть - удаляй, нет - игнорируй.

2024-06-04 10:31 UTC, MaxwellDevelopments commented on src/test/java/stellarburger/tests/ConstructorPanelTests.java
> +        isElementSelected(selectedIngredientType);
Ой как я с этим тестом намучался на самом деле. Он вроде и очень простой, но там проблема с кликом нервы попортила. Вроде как почитал, что через js можно решить. Сейчас попытаюсь исправить. Я и сам думал, что с switch-case какая-то лажа получилась.

2024-06-04 10:32 UTC, MaxwellDevelopments commented on src/test/java/stellarburger/tests/ConstructorPanelTests.java
> +        MatcherAssert.assertThat(cssClass, containsString("current"));
факт

2024-06-06 19:04 UTC, pavel-ulan approved these changes
Валидно =)

2024-06-06 19:04 UTC, pavel-ulan commented on src/test/java/stellarburger/tests/ConstructorPanelTests.java
> +    }
ну вот и смотрится получше, не правда ли? =)
Отлично сделано 👍

2024-06-08 09:47 UTC, merged